/* Generated by MyraPad at 6/3/2026 3:27:19 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class ChooseTextureRegionDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Filter:";

			_textFilter = new TextBox();
			_textFilter.Id = "_textFilter";
			StackPanel.SetProportionType(_textFilter, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(_textFilter);

			var label2 = new Label();
			label2.Text = "Image";

			var label3 = new Label();
			label3.Text = "Size";
			Grid.SetColumn(label3, 1);

			var label4 = new Label();
			label4.Text = "NP";
			Grid.SetColumn(label4, 2);

			var label5 = new Label();
			label5.Text = "Name";
			Grid.SetColumn(label5, 3);

			var grid1 = new Grid();
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			
			
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 60,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 50,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(label5);

			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("icon-folder");
			image1.Width = 32;
			image1.Height = 32;
			Grid.SetRow(image1, 1);

			var label6 = new Label();
			label6.Text = "32x32";
			label6.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label6, 1);
			Grid.SetRow(label6, 1);

			var checkButton1 = new CheckButton();
			checkButton1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			checkButton1.Enabled = false;
			Grid.SetColumn(checkButton1, 2);
			Grid.SetRow(checkButton1, 1);

			var label7 = new Label();
			label7.Text = "icon-folder";
			label7.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label7, 3);
			Grid.SetRow(label7, 1);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("icon-star");
			image2.Width = 32;
			image2.Height = 32;
			Grid.SetRow(image2, 2);

			var label8 = new Label();
			label8.Text = "32x32";
			label8.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label8, 1);
			Grid.SetRow(label8, 2);

			var checkButton2 = new CheckButton();
			checkButton2.IsChecked = true;
			checkButton2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			checkButton2.Enabled = false;
			Grid.SetColumn(checkButton2, 2);
			Grid.SetRow(checkButton2, 2);

			var label9 = new Label();
			label9.Text = "icon-star";
			label9.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label9, 3);
			Grid.SetRow(label9, 2);

			_gridData = new Grid();
			_gridData.RowSpacing = 4;
			_gridData.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			
			
			_gridData.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 60,
			});_gridData.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});_gridData.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 50,
			});_gridData.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridData.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridData.Id = "_gridData";
			_gridData.Widgets.Add(image1);
			_gridData.Widgets.Add(label6);
			_gridData.Widgets.Add(checkButton1);
			_gridData.Widgets.Add(label7);
			_gridData.Widgets.Add(image2);
			_gridData.Widgets.Add(label8);
			_gridData.Widgets.Add(checkButton2);
			_gridData.Widgets.Add(label9);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 4;
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(_gridData);

			var scrollViewer1 = new ScrollViewer();
			StackPanel.SetProportionType(scrollViewer1, Myra.Graphics2D.UI.ProportionType.Fill);
			scrollViewer1.Content = verticalStackPanel1;

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Spacing = 8;
			verticalStackPanel2.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel2.Widgets.Add(scrollViewer1);

			
			Title = "Choose Texture Region";
			Left = 363;
			Top = 150;
			Width = 600;
			Height = 600;
			Content = verticalStackPanel2;
		}

		
		public TextBox _textFilter;
		public Grid _gridData;
	}
}
