/* Generated by MyraPad at 6/6/2026 7:22:06 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class FontEditorDialog: Dialog
	{
		private void BuildUI()
		{
			_textValue = new TextBox();
			_textValue.Readonly = true;
			_textValue.Width = 400;
			_textValue.Id = "_textValue";

			var label1 = new Label();
			label1.Text = "Set Image From Stylesheet";

			_buttomSetFromStylesheet = new Button();
			_buttomSetFromStylesheet.Id = "_buttomSetFromStylesheet";
			_buttomSetFromStylesheet.Content = label1;

			var label2 = new Label();
			label2.Text = "Set Image From External File";

			_buttonSetFromFile = new Button();
			_buttonSetFromFile.Id = "_buttonSetFromFile";
			_buttonSetFromFile.Content = label2;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_textValue);
			verticalStackPanel1.Widgets.Add(_buttomSetFromStylesheet);
			verticalStackPanel1.Widgets.Add(_buttonSetFromFile);

			
			Title = "Font Editor";
			Left = 458;
			Top = 378;
			Content = verticalStackPanel1;
		}

		
		public TextBox _textValue;
		public Button _buttomSetFromStylesheet;
		public Button _buttonSetFromFile;
	}
}
